server:
  port: 9001

spring:
  application:
    name: auth-service

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka

