server:
  port: 9001

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_db
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  secret: n4EpjnNy7x8FjfwYMDjPi8xYyL0EocN1uzUsfFTbLhk=
  expiration: 86400

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka

