spring:
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: "http://${CONFIG_URI:localhost:8888}"
  application:
    name: gateway-service

server:
  port: 8080

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always