server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:aremm23/modsen-library-config.git
          clone-on-start: true
          default-label: master
          private-key: ./id_ed25519